services:
  - type: web
    name: somapoa-backend
    env: python
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    plan: free
    envVars:
      - fromGroup: somapoa-env
