services:
  - type: web
    name: somapoa-backend
    env: python
    buildCommand: pip install -r server/requirements.txt
    startCommand: gunicorn server.app:create_app()
    plan: free
    envVars:
      - fromGroup: somapoa-env
    rootDir: server
