services:
  - type: web
    name: somapoa-backend
    env: python
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: bash -c "flask db upgrade && gunicorn wsgi:app"
    plan: free
    envVars:
      - fromGroup: somapoa-env
