"""Add OTP fields

Revision ID: ad14f8a745ef
Revises: c66ccc271990
Create Date: 2025-07-19 16:48:23.293806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad14f8a745ef'
down_revision = 'c66ccc271990'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_secret', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('otp_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('otp_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('otp_expiry')
        batch_op.drop_column('otp_verified')
        batch_op.drop_column('otp_secret')

    # ### end Alembic commands ###
