"""Fix email column type

Revision ID: 920abd843d2e
Revises: ef4b068a6e35
Create Date: 2025-06-24 14:53:49.626138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '920abd843d2e'
down_revision = 'ef4b068a6e35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
